# Generated by Django 5.2.3 on 2025-07-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='producr',
            new_name='product',
        ),
    ]
